apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-tier
  namespace: three-tier-app
spec:
  selector:
    matchLabels:
      app: web-tier
  template:
    metadata:
      labels:
        app: web-tier
    spec:
      containers:
      - name: web-tier
        image: mzchievous/web-tier:k8s-v1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-tier
  namespace: three-tier-app
spec:
  type: NodePort
  selector:
    app: web-tier
  ports:
  - port: 8080
    targetPort: 80
    